x-default-opts: &default-opts
  restart: unless-stopped
  tty: true
  stdin_open: true
  privileged: false
  ipc: private
  networks:
    - ow-network

services:
  traefik:
    image: traefik:v3.7.4
    container_name: ow-dev-traefik
    <<: *default-opts
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ow-network"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    extra_hosts:
      - "host.docker.internal:host-gateway" # 💥 讓 Traefik 容器能連回宿主機的 3000 和 5173
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic

  postgresql:
    image: postgres:18-alpine
    container_name: ow-dev-postgres
    <<: *default-opts
    ports:
      - "55432:5432"
    environment:
      - TZ=Asia/Taipei
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - server-dev-pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  ow-network:
    external: true

volumes:
  server-dev-pgdata:
