http:
  services:
    api-service:
      loadBalancer:
        servers:
          - url: "https://host.docker.internal:3000"
        serversTransport: api-insecure

    web-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"
