http:
  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    web-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"
