services:
  opencode:
    container_name: ow-opencode
    image: tsukisama9292/private-images:ow-opencode
    build:
      context: ../..
      dockerfile: docker/personal-dev/Dockerfile

    user: "1000:1000"

    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    ipc: private
    volumes:
      - ../../:/home/user/workspace/OpenWorkspace-Engine/
      - ~/.local/share/opencode/:/home/user/.local/share/opencode/
#     networks:
#       - usb_macvlan

# networks:
#   usb_macvlan:
#     driver: macvlan
#     driver_opts:
#       parent: enx1a4d793aeca5
#     ipam:
#       config:
#         - subnet: 10.122.78.0/24
#           gateway: 10.122.78.89