http:
  routers:
    # 1. API 路由：存取 http://localhost/api... 轉發給 3000
    api-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/api`)"
      service: "api-service"

    # 2. 前端路由：存取 http://localhost/... 轉發給 5173
    web-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: "web-service"

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    web-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"