ARG VERSION=jammy

FROM ubuntu:${VERSION}

EXPOSE 7681

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    sudo \
    curl \
    git \
    wget \
    openssl \
    ttyd \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash ow_user
# ow_user is allowed to run apt commands without a password prompt
RUN echo "ow_user ALL=(ALL) NOPASSWD: /usr/bin/apt, /usr/bin/apt-get" > /etc/sudoers.d/ow_user \
    && chmod 0440 /etc/sudoers.d/ow_user

# Set directory permissions for ow_user
RUN chown -R ow_user:ow_user /etc/ssl/private /etc/ssl/certs

COPY ./entrypoint/entrypoint_ttyd.sh /home/ow_user/entrypoint.sh
RUN chmod +x /home/ow_user/entrypoint.sh

USER ow_user
WORKDIR /home/ow_user

ENTRYPOINT ["/home/ow_user/entrypoint.sh"]