ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

### Override Kasm branding with custom images
COPY ./src/images/bg_jammy.png /usr/share/backgrounds/bg_kasm.png
COPY ./src/images/bg_jammy.png /usr/share/backgrounds/bg_default.png
COPY ./src/images/icon_ubuntu.png /usr/share/extra/icons/icon_kasm.png
COPY ./src/images/icon_ubuntu.png /usr/share/extra/icons/icon_default.png
COPY ./src/images/icon_ubuntu.png /usr/share/extra/icons/icon_ubuntu.png

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/scripts/install_chrome.sh \
                  /scripts/install_dev_common_tools.sh \
                  /scripts/install_dbeaver.sh \
                  /scripts/install_uv.sh \
                  /scripts/install_chromium.sh \
                  /scripts/install_vs_code.sh \
                  /scripts/install_opencode.sh \
                  /scripts/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}


# kasm-user is allowed to run apt commands without a password prompt
RUN echo "kasm-user ALL=(ALL) NOPASSWD: /usr/bin/apt, /usr/bin/apt-get" > /etc/sudoers.d/kasm-user \
    && chmod 0440 /etc/sudoers.d/kasm-user

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]